version: "3.8"

services:
  app:
    image: discord-rotate-bot
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start
    environment:
      - NODE_ENV=development
    restart: unless-stopped
